language: php
php:
  - '5.6'
  - '7.0'

addons:
  postgresql: "9.4"
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm -g install npm@next
  - npm install --global gulp-cli
  - gulp --production
  - php artisan key:generate
  - php artisan migrate --seed

before_install:
  - psql -c 'create database filoq_gestion_test;' -U postgres
  - psql -c 'create database filoq16_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
  - export PGPASSWORD="12345678"

services:
  - postgresql
cache:
  directories:
    - node_modules
    - vendor

script:
  - vendor/bin/phpunit


